version: '3.8'

services:
  # 后端API服务
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  worker:
    build: 
      context: ./backend
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - backend
    command: celery -A app.worker.celery_app worker --loglevel=info

  # Redis服务
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # 前端服务
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    command: npm start

volumes:
  redis-data:
